### ISSUE TITLE
如何引入手写的MyModule?

### ISSUE THREAD

**Issue by feiaaa** [dennis-jiang/Front-End-Knowledges#73]
关于这个代码[mymodule](https://github.com/dennis-jiang/Front-End-Knowledges/blob/master/Examples/Node.js/Module/MyModule/index.js
)
我把他贴到一个新建的项目的```MyModules```文件夹里,以index.js命名，想要试用一下。
并且在同级的目录里贴入了上述项目中的a.js文件和调用a的use.js文件。
use.js 的代码如下
```
const MyModule= require("./index.js") 

const a = MyModule.require('./a.js'); // 这段用require('./a.js');没问题
console.log(a,"=use.js");
```
然后 ```node ./MyModules/use.js``` 报错；
```TypeError: MyModule.require is not a function```

**Comment by suzhenghui-sky** [comment]
MyModule.require，MyModule有这个方法嘛？

**Comment by feiaaa** [comment]
> MyModule.require，MyModule有这个方法嘛？

```MyModule.prototype.require ```

**Comment by suzhenghui-sky** [comment]
mymodule 中根本就没有导出的语句，所以无法导入；你完全可以打印下看看你导出的变量有没有值，如果你想要引用的话就用 import "./index.js"

**Comment by feiaaa** [comment]
在MyModules最后加了2行,导出和require，然后在另一个文件中使用（只能require modules 否则 报错Cannot use import statement outside a module）
```
MyModule.require = MyModule.prototype.require;
module.exports = MyModule;
```
```
const MyModule= require("./index.js")
const a = MyModule.require('./MyModules/a.js');
console.log(a,"=use.js");
```
